name: "Snyk CICD Scan"

on:
  push:
    branches:
      - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}
      # Run Snyk SCA
      - name: Run Snyk SCA
        run: |
          snyk test --severity-threshold=high
        continue-on-error: true

        # Run Snyk Monitor
      - name: Run Snyk Monitor
        run: |
          snyk monitor --severity-threshold=high
        continue-on-error: true
